version: '2'
services:
  app:
    container_name: app
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/sampleapp
    links:
      - db
  db:
    image: postgres:9.6.2-alpine
    container_name: pg
    ports:
      - '5432:5432'